### ISSUE TITLE
Fetching CoreDNS metrics fails with default configuration on EKS

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-prometheus#154] opened 2021-04-16 13:08 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

With default configs, scraping CoreDNS metrics installed on EKS cluster by default fails with the following logs:
```
time="2021-04-16T12:06:54Z" level=info msg="Starting New Relic's Prometheus OpenMetrics Integration version 2.4.0"
time="2021-04-16T12:06:54Z" level=info msg="Running in standalone mode..."
time="2021-04-16T12:06:59Z" level=warning msg="fetching Prometheus metrics: http://kube-dns.kube-system.svc:9153/metrics (kube-dns)" component=Fetcher error="Get \"http://kube-dns.kube-system.svc:9153/metrics\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2021-04-16T12:06:59Z" level=warning msg="error while scraping target" component=Fetcher error="Get \"http://kube-dns.kube-system.svc:9153/metrics\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2021-04-16T12:07:02Z" level=warning msg="fetching Prometheus metrics: http://newrelic-bundle-kube-state-metrics.newrelic.svc:8080/metrics (newrelic-bundle-kube-state-metrics)" component=Fetcher error="Get \"http://newrelic-bundle-kube-state-metrics.newrelic.svc:8080/metrics\": dial tcp 10.100.88.203:8080: connect: connection refused"
```

It seems to be directly related to https://github.com/weaveworks/eksctl/issues/936.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

With default EKS configuration and default nri-prometheus configuration, metrics are scraped properly.

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

1. Create EKS cluster
2. Install `nri-bundle` helm chart with the following configuration:
```yaml
global:
  licenseKey: <your license>
  cluster: fargate-test
newrelic-infrastructure:
  privileged: false
ksm:
  enabled: true
prometheus:
  enabled: true
kubeEvents:
  enabled: true
logging:
  enabled: false
```
## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

```
$ eksctl  version
0.44.0
```

```
$ helm ls
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
newrelic-bundle newrelic        2               2021-04-16 14:09:52.708143328 +0200 CEST        deployed        nri-bundle-2.7.1        1.0
```
## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by paologallinaharbur** [comment] 2021-06-10 12:38
Also related to https://github.com/aws/containers-roadmap/issues/965

**Comment by paologallinaharbur** [comment] 2021-06-10 12:41
A possible solution is even if there is a label specifying the port verifying with the service/endpoints that that port is actually available:

Root cause:
```
$ kubectl get services -n kube-system  -o yaml
[...]
    annotations:
      prometheus.io/port: "9153"
      prometheus.io/scrape: "true"
[...]
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
[...]
```

**Comment by paologallinaharbur** [comment] 2021-06-10 12:46
The only workaround for now is to set manually in the annotation of the service "prometheus.io/scrape: "false"" or to add the port in the service verifying that coreDNS is configured to provide prometheus output

**Comment by invidian** [comment] 2021-06-10 12:49
>The only workaround for now is to set manually in the annotation of the service "prometheus.io/scrape: "false"" or to add the port in the service verifying that coreDNS is configured to provide prometheus output

I guess this will be overwritten by EKS controlplane?

**Comment by paologallinaharbur** [comment] 2021-06-10 12:53
So far in my cluster it did not, but you are right I am not sure if at some point it will

**Comment by LeSandeep** [comment] 2021-06-16 18:44
Hi @paologallinaharbur - saw that https://github.com/newrelic/nri-prometheus/issues/190 was closed in favor of this issue, which is fine, but I want to point out that the issue I was trying to report is _not_ that I'm unable to scrape `coredns` metrics from the `Service`, rather that I would like the metrics to be scraped from the individual coredns _pods_.

I think there is a reason behind `kube-dns` service not exposing port `9153` - because any metrics fetched from the service will be load balanced to the `coredns` pods and hence we won't be able to see accurate numbers for _all_ DNS lookups within the cluster. Apparently this was fixed in https://github.com/newrelic/nri-prometheus/pull/148 ? But I'm unable to get that to work. Any help is appreciated

**Comment by paologallinaharbur** [comment] 2021-06-17 09:10
Hello @LeSandeep, my mistake, I was sure that the issue was related. but after reviewing again it seems it is not, I will reopen that one and we can continue on #190 to avoid mixing the topics.
Thanks for highlighting that!

**Closed** 2022-10-07 12:39 UTC
