### ISSUE TITLE
Consider using Prometheus itself for targets discovery and scraping

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-prometheus#198] opened 2021-06-09 07:21 UTC
As Prometheus already implements discovery and scraping logic, perhaps we could use it and e.g. configure it to do a remote write to this integration, so then we can convert Prometheus metrics to NewRelic metrics and send them to backend.

Prometheus most likely has more robust code for scraping, so this might bring performance benefits.

Example of remote write server: https://github.com/prometheus/prometheus/blob/db7f0bcec27bd8aeebad6b08ac849516efa9ae02/documentation/examples/remote_storage/example_write_adapter/server.go#L28

Right now `internal/integration` package relies on deprecated `MetricFamily` (#196). If we would change it to use more up to date https://pkg.go.dev/github.com/prometheus/common/model, then switching to remote write server should be trivial.

**Comment by invidian** [comment] 2021-06-09 13:11
It seems newer version of prometheus support sending metadata as part of remote writerequest, so with this data, it should be easy to convert it back to MetricFamily if needed: https://pkg.go.dev/github.com/prometheus/prometheus@v1.8.2-0.20210518124745-db7f0bcec27b/prompb#MetricMetadata.

**Comment by invidian** [comment] 2021-06-09 21:10
Regarding alternative of using Prometheus as a library, it doesn't seem feasible because:
- Configuring scraping and storage is currently not exported from Prometheus CLI package and contains 1000+ lines of code.
- Scraper itself does not provide much information about collected metrics, so implementing it will possibly require 
 a lot of code to convert from scraped format to format expected by integration. See https://pkg.go.dev/github.com/prometheus/prometheus@v1.8.2-0.20210518124745-db7f0bcec27b/scrape#NewManager.

**Comment by invidian** [comment] 2021-06-11 10:07
Hmm, according to:
- https://cloud.ibm.com/docs/monitoring?topic=monitoring-prometheus_remote_write#prometheus_remote_write_limitations
- https://docs.sysdig.com/en/-beta--prometheus-remote-write.html

And what I understand from the code, when using remote write you do not get summary metrics or histograms data, only plain values, so I'm not sure if we can make use of it without some breaking changes.

**Comment by invidian** [comment] 2021-06-16 18:31
After discussing it internally, one thing which came up was that perhaps we can look into https://github.com/open-telemetry/opentelemetry-collector, how they re-use prometheus as a library, and perhaps what are the missing features we use right now, which would not be possible if we use prometheus for scraping.


Perhaps we can also look again into remote write protocol, see how easy would it be to re-construct the existing metric requirement. I found https://pkg.go.dev/github.com/prometheus/common/model#pkg-constants, which might be helpful.

**Comment by davidgit** [comment] 2022-09-29 07:50
Duplicate of [#334 ](https://github.com/newrelic/newrelic-coreint/issues/334)

**Closed by davidgit** 2022-09-29 07:50 UTC
Labels: feature, design
