### ISSUE TITLE
Nri-prometheus scraping and parsing issue

### ISSUE THREAD

**Issue by Pinky-Chaudhary** [newrelic/nri-prometheus#326] opened 2022-07-25 06:30 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
We are having some trouble understanding why the nri-prometheus scraper is not correctly getting the right values. For example we have a simple counter metric like this that is scraped.

http_counter_for_api_call_total{app_name="prediction”,method=“POST”,requests_processed=“1”,time=“11.634642839431763”,uri="/prediction/predict"} 1.0

What we are seeing is the scraper decrements that value. So if the value here is 1.0, the scraped value appears to be 0. If the value is 2.0, the scraper sets the value to 1 and so on.

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
we have a fastapi microservices with few api endpoints, we are using starllete-middleware PrometheusMiddleware to get count of api requests.We are exposing metrics at /metrics route and using nri-prometheus to scrape it but we are seeing unusual behaviour. In /metrics endpoint we can see count is increasing for each request, for first request its value count shows 1, but nri-prometheus logs is showing value count=0 , same result while performing aggregation functions on specific metrics.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
nri-prometheus should be returning value 1 for each api request for Counter metrics but it is returning 0.

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
Here’s a snippet of the audit log from the scraper.
{“name”:“http_counter_for_api_call_total”,“type”:“count”,“value”:0,"t imestamp":1658408035172,“[interval.ms](http://interval.ms/)”:34840,“attributes”:{“app_name”:“prediction”,“clusterName”:“dal09-dev-ocp-01”,“collector.name”:“nri-prometheus”,“collector.version”:“2.13.0”,“deploymentName”:“prediction”,“instrumentation.name”:“nri-prometheus”,“instrumentation.provider”:“newRelic”,“instrumentation.version”:“2.13.0”,“integrationName”:“nri-prometheus”,“integrationVersion”:“2.13.0”,“k8s.cluster.name”:“dal09-dev-ocp-01”,“[label.app.kubernetes.io/instance](http://label.app.kubernetes.io/instance)”:“prediction”,“promMetricType”:“counter”,“requests_processed”:“1”,“scrapedTargetKind”:“pod”,“scrapedTargetName”:“prediction-xxxx”,“scrapedTargetURL”:“http://x.x.x.x/:xxxx/metrics”,“targetName”:“prediction-xxxxx”,“time”:“11.564742803573608”,“uri”:"/prediction/predict"}},

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
openshift pod

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by Pinky-Chaudhary** [comment] 2022-07-25 06:32
@paologallinaharbur can you please help in understanding this behaviour or nri-prometheus scrapper, these metrics is critical for in our application .

**Comment by paologallinaharbur** [comment] 2022-07-25 09:40
Hello! In nri-prometheus we are leveraging the telemetry SDK. In particular whenever a counter is scraped the delta is computed. Example:

```
Scraped valued  15  16  20 30 30
Delta reported   0   1  4  10  0 
```

The first value scraped is not considered to send a delta (considering the previous value as 0) even with only one account. Skipping the first value scraped was a design choice taken to avoid sending wrong data after a restart of the integration

**Comment by Pinky-Chaudhary** [comment] 2022-07-25 17:24
Yes, I read those in documentation, but in our case we need the count for each api request and have one specific label which differentiate each request , can you please advice which metrics can be used here if not Counter?

**Comment by paologallinaharbur** [comment] 2022-07-25 20:27
The metric dimensions seems having outbounded cardinality. Why do you have `requests_processed` and `time` as dimensions?

https://prometheus.io/docs/practices/naming/#labels
> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

If you have `time` as dimension, then each request is a new time series. Therefore the first delta is never taken into consideration since each request will generate a new time series and no delta can be computed.
```
Scraped valued  1 1 1 
Delta reported   0 0 0
```

**Comment by paologallinaharbur** [comment] 2022-07-26 08:09
Yes you can do it, but you have already the timestamp each time a sample is collected.

However, If I understood correctly you are trying to create a different time series per request. That goes out a bit from the prometheus scope. You should check the docs regarding how to write an exporter and which metrics should be collected using different tools -> https://prometheus.io/docs/instrumenting/writing_exporters/#labels

**Comment by paologallinaharbur** [comment] 2022-07-26 08:10
closing this since it is expected behaviour, thanks for reaching out

**Closed by paologallinaharbur** 2022-07-26 08:10 UTC
